server:
  error:
    include-message: always
    include-binding-errors: always

iugu:
  api:
    token: AFEC68916DC4274E923FAA3FCE2E55EF4B19F957D40C23F39049451947AD5E90
    account: 07366109AA6644B8BB51D9DC6EBC4D6D

spring:

  web:
    resources:
      static-locations: classpath:/public/

  h2:
    console:
      enable: true

  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:godev
    password:
    username: sa
